apiVersion: v2                                                                               
name: dreamteams-ingress                                                                     
description: Traefik routing for DreamTeams                                                  
type: application                                                                            
version: 0.1.0