traefik:
  name: traefik
  namespace: kube-system

deployment:
  kind: DaemonSet

service:
  externalTrafficPolicy: Local

logs:
  access:
    enabled: false

ports:
  web:
    redirectTo:
      port: websecure
      scheme: https
      permanent: true
