replicaCount: 4

image:
  repository: ghcr.io/lubaskinc0de/dreamteams
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: ghcr-secret

nameOverride: "dreamteams-api"
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 750m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /internal/alive
    port: http
readinessProbe:
  httpGet:
    path: /internal/ready
    port: http
startupProbe:
  httpGet:
    path: /internal/alive
    port: http
  periodSeconds: 5
  failureThreshold: 72

analysis:
  initialDelay: 10s
  interval: 10s
  count: 6
  failureLimit: 1
  successCondition: result[0] < 5
  failureCondition: result[0] >= 5
  minimumRequests: 20
  queryWindow: 1m

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

command:
  - dreamteams
  - run
  - api

env:
  APP_CONFIG_PATH: "/etc/dreamteams/config.toml"

config:
  existingSecret: dreamteams-api-config
  key: config.toml

waitFor:
  - name: pgbouncer
    host: dreamteams-pgbouncer
    port: 6432
