apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamteams-authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:lubaskinc0de/dreamteams-deploy.git
    targetRevision: HEAD
    path: dreamteams_authentik
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
