apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamteams-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: git@github.com:lubaskinc0de/dreamteams-deploy.git
    targetRevision: HEAD
    path: dreamteams_frontend
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: runtimeConfig.apiBase
          value: https://dreamteams.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: dreamteams
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
