apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamteams-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:lubaskinc0de/dreamteams-deploy.git
    targetRevision: HEAD
    path: dreamteams_ingress
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: issuerName
          value: dreamteams-prod
        - name: appHost
          value: dreamteams.luba.skin
        - name: authHost
          value: auth.dreamteams.luba.skin
        - name: grafanaHost
          value: grafana.dreamteams.luba.skin
        - name: s3Host
          value: s3.dreamteams.luba.skin
        - name: logout.endSessionUrl
          value: https://auth.dreamteams.luba.skin/application/o/dreamteams/end-session/
        - name: logout.postLogoutRedirectUrl
          value: https://dreamteams.luba.skin/
        - name: apiDocsAccess.enabled
          value: "true"
        - name: securityHeaders.stsSeconds
          value: "31536000"
        - name: securityHeaders.stsIncludeSubdomains
          value: "true"
        - name: securityHeaders.stsPreload
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: dreamteams
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
