apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: {{ .Values.traefik.name }}
  namespace: {{ .Values.traefik.namespace }}
spec:
  valuesContent: |-
    deployment:
      kind: {{ .Values.deployment.kind }}
    service:
      spec:
        externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
    logs:
      access:
        enabled: {{ .Values.logs.access.enabled }}
    {{- if .Values.plugins.simpleCache.enabled }}
    experimental:
      plugins:
        simplecache:
          moduleName: {{ .Values.plugins.simpleCache.moduleName | quote }}
          version: {{ .Values.plugins.simpleCache.version | quote }}
    {{- end }}
    {{- if .Values.ports.anubis.enabled }}
    additionalArguments:
      - "--entrypoints.anubis.address=:{{ .Values.ports.anubis.port }}"
    {{- end }}
    ports:
      web:
        redirectTo:
          port: {{ .Values.ports.web.redirectTo.port }}
          scheme: {{ .Values.ports.web.redirectTo.scheme }}
          permanent: {{ .Values.ports.web.redirectTo.permanent }}
