apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamteams-local-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:lubaskinc0de/dreamteams-deploy.git
    targetRevision: HEAD
    path: local
  destination:
    server: https://kubernetes.default.svc
    namespace: dreamteams
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
