apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
{{ .Files.Get "prometheus.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector.yaml: |
{{ .Files.Get "otel-collector.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
{{ .Files.Get "loki.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
{{ .Files.Get "tempo.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.yaml: |
{{ .Files.Get "vector.kubernetes.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  datasources.yml: |
{{ .Files.Get "grafana/provisioning/datasources/loki.yml" | indent 4 }}
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: dreamteams
        orgId: 1
        folder: DreamTeams
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
{{ (.Files.Glob "grafana/provisioning/dashboards/*.json").AsConfig | indent 2 }}
