postgresql:
  auth:                                                                                      
    existingSecret: dreamteams-postgres-secret                                               
    secretKeys:                                                                              
      adminPasswordKey: postgres-password
      userPasswordKey: password
    username: postgres
    database: postgres
  primary:
    persistence:
      size: 1Gi