replicaCount: 1

image:
  repository: edoburu/pgbouncer
  tag: v1.23.1-p3
  pullPolicy: IfNotPresent

nameOverride: dreamteams-pgbouncer
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 6432

postgres:
  host: dreamteams-postgres-postgresql
  port: 5432
  database: postgres

secret:
  existingSecret: dreamteams-pgbouncer-secret
  userKey: DB_USER
  passwordKey: DB_PASSWORD
  adminUserKey: PGBOUNCER_ADMIN_USER
  adminPasswordKey: PGBOUNCER_ADMIN_PASSWORD

pool:
  mode: transaction
  maxClientConn: "1000"
  defaultPoolSize: "200"
  reservePoolSize: "20"
  reservePoolTimeout: "3"
  serverLifetime: "3600"
  serverIdleTimeout: "600"
  maxPreparedStatements: "100"

resources:
  requests:
    cpu: 25m
    memory: 48Mi
  limits:
    cpu: 300m
    memory: 192Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 70
  runAsGroup: 70
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 70
  runAsGroup: 70

nodeSelector: {}
tolerations: []
affinity: {}
