# k3s version to install on the server                                                     
k3s_version: "v1.32.2+k3s1"                                                                  
                                                                                              
# ArgoCD version to install                                                                  
argocd_version: "v2.14.3"                                                                    
                                                                                              
# Kubernetes namespace where ArgoCD lives
argocd_namespace: argocd

# Kubernetes namespace where your app services run
app_namespace: dreamteams

# Your deploy repo (ArgoCD watches this)
deploy_repo: git@github.com:lubaskinc0de/dreamteams-deploy.git

# Linux user created for managing the k3s cluster.
cluster_user: deploy

# Your local SSH public key — added to the cluster user's authorized_keys.
# Get it with: cat ~/.ssh/id_ed25519.pub
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYd/QhHYQRdN/STbkfam11ZfAcKQv8yrrIWATGj5yQY structnull@yandex.ru"