apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "dreamteams_api.fullname" . }}-5xx-rate
  labels:
    {{- include "dreamteams_api.labels" . | nindent 4 }}
spec:
  metrics:
    - name: http-5xx-rate
      initialDelay: {{ .Values.analysis.initialDelay | quote }}
      interval: {{ .Values.analysis.interval | quote }}
      count: {{ .Values.analysis.count }}
      failureLimit: {{ .Values.analysis.failureLimit }}
      successCondition: {{ .Values.analysis.successCondition | quote }}
      failureCondition: {{ .Values.analysis.failureCondition | quote }}
      provider:
        prometheus:
          address: http://prometheus.observability:9090
          query: |
            (
              ((sum(increase(http_server_duration_milliseconds_count{service_name="dreamteams"}[{{ .Values.analysis.queryWindow }}])) or vector(0)) >= bool {{ .Values.analysis.minimumRequests }})
              *
              (
                ((sum(rate(http_server_duration_milliseconds_count{service_name="dreamteams", http_status_code=~"5.."}[{{ .Values.analysis.queryWindow }}])) or vector(0))
                /
                clamp_min((sum(rate(http_server_duration_milliseconds_count{service_name="dreamteams"}[{{ .Values.analysis.queryWindow }}])) or vector(0)), 0.001))
                * 100
              )
            )
