apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dreamteams_api.fullname" . }}-config
  labels:
    {{- include "dreamteams_api.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.configFile | nindent 4 }}