{{- if not .Values.externalSecret }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dreamteams_api.fullname" . }}-secret
  labels:
    {{- include "dreamteams_api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}