---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dreamteams-migrations-migrations-secret
  namespace: dreamteams
spec:
  encryptedData:
    APP_DB_PASSWORD: AgBGTSTP03zYlTrWEF4No/kj3kMBr+Pj2Z/tJYRkdr/P967gExbvRiFddhRCkQzia9rVVM1qYu07Spbr8jVF9mK+JlBan2TxBi16WrJrR1s9NSa1UfuzMB9fDawZGIaZNP/HHmVPC4SQyOvfOnYO6qZKyqISf1hXE4/xDNT7MmvvyM+RuBP31hIOHf+sOfmV8vAyafzQQnYnZzhvjLnuF7kYG5q88hE2JnjUbHiKMIZ+T+Pn8eTiswYKacc0Jb8ZPGUG/MF0GDgOQ+mquKGv6TBs8081YKlVtWSCrxTrBPStXeqckfYVHXZkQ1cC/3eQ7ij4peRAEgJHVo7mZSISaFw0DmHJZbD4GpR6jnmhIIgK31qT5XouKzRuZH7S9S9CIns1GFYIei5iht/svx/NkokLNXkmOPe3Z6uFmuLSQXMA8LBNJyNM9BYz+dNoT64LEYnWeeTQF41g2NaccB6GXs6aHK7WUlA0U7N01bP8zg1w0wV8uyGQeTycP9E8yTldHDju29KW9w/p866jo1zC3Jb/+Dea/lIwKJsenSP5ZA27jqCcf8ucAHOb8iaoF3l8U/1HTfkv5pwtXSQQC0X1ixyxMiMAuHSyb9HqI9Obu5mCr4Bz/YdRvZyUrvAC6k+fL3f7lA5RLHTRfZyhSjjdMqXDB76Mxqdb25o30rHh4A203dsimgWPMCCJ/DoUeAQtCPlGUdikvznm1w==
    APP_DB_USER: AgAZKlqKtZBPGLEswrBvCmXDdPuJNUxaahBFw1WXJLST3MYjmld0yU4wHSjjLYZ2uLDX6jfeROJOzFS8uzoxX32ZrNaG3bD9pcDD9pnGryotqjwdCPcxtbQLTLys+2eKPZ9ZXuXWSU7QY90jNiCuJCPqs4tCv2R4GMSp2oivm+qjYZgqtSO4R4gHC3gCsC5aXkv7UZm+26cug4nB68HThDuAgeIhVF9jFIkRrEoyAG+nTEiRKfIrQWWdJo0C4P6GRCRZanQWpu5L3kfF6c3f6W2O15cstnQvjtQ1pfS8L2MOIh2LA8vf9AGrdctaqRr7pnj6ojaw/fQMtt0brrLce+ND8eMB9PQ+u0gFsNHQMcYXv0wTynNFAD8angtcsM9uNo8OdvZgUbEYAk82gHQTavhzcUwcgqxqRXhSLgSErpui7AV360zjo77p56ueyO+oXzWxJ6+kF6WbzwYyGNfyo5VW12rBG95DINvaH4F6cimj8zWeAXIzbC0px02MG962QwRx+38AADb47uJTEPseiXzINlni0o0bEYp3Slb8eAK5qIZHng7aOPH7sGf0vbzCdRDmnkj9JhT5Gfl3dXjhsyc9yVYSc+vG9H0hO1nfcqZPiUO0jK4sBfkHMuh5YJmyxypmIClgzovVDGjsyiexQzvtBIVO03qpol0QZIcyAcyv+upOwu7Fnn1jLaSw9kGCP33pczIOZqMIRQ==
  template:
    metadata:
      name: dreamteams-migrations-migrations-secret
      namespace: dreamteams
    type: Opaque
