---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dreamteams-postgres-secret
  namespace: dreamteams
spec:
  encryptedData:
    password: AgBcU/O+6ii4Sg8B4R/OCwEED7FLrAGgnhCdgEaCBSyeR3yle/DUhmWcekhgkaz35dzFpG8+gg2CG6GdVkTLorMmwJJCXES0uE/3XsvFLm0B0L65HFAsvkgrZAlpJwbNn66wD0jyvrPQxjQANODCVVQxs9ekF1prBUGnvja2Ii95UmtCAZxLQadr7SJ4xcUJJKXA/tNdzbh8EoJDe+Nhm9FBrZ1IB9yM4UKn7MreeVnbMk+JcHENlyDKmTpLyhiL6jNq0G9ZAeYjLYJw8WyhuD4hCID8IOSD6E1dNRSLT1Y9Kuw6h2+bzClwfwzwur0AFAhQz/MPKOs6mtIAsXbRNAoBXugkvOLrWMtjyM/ipNMx2vgDA4H0kwKV5+NVUzO2/8ahy3Lrn+a/4MU0b4otpNguqeew9qV3OrtBqFi3br2HIkpxcI2nnZvjw3RUvlN2SSRQ9Jco2KEUjM1ScnHqpBUA1KZpFKqOHrfPVGeSezr7hrXET1tcgh1GYMdVmzjipf2MqSaK4jA79Tq7dVAYXCGjSO4DXFr+12RYsS3vlcCWj0NSp3aS5DA02nr5kuHNZPeXHy0OmriyNw5YUM05m4YZ/9mySBSkB3H+SWugalElOLstkZ/m3LfklEXJftZIVz6pfLyGewxUb31j1hfxnscIaLztFL5CifjLs0TeU/qKYx17CFzKcOLpfgw/K7IAJ/HHkrrga5IASg==
    postgres-password: AgCCb2eMr27aMQDNKei5zQDT4Kg8lxxQGsmeDTD1mK84alt0NtLwzTo26yyfsgqSuR9pLi0GwV3cyUX3KUcpHyVgx5OVxphl2F6/vHPJRJQGa5WZNN2YOSHt3qRBmfyRHTL1zlceWhkwP6E3p9jstF4JmnXYoBo0XgSjuseK7xPUodwIxeX6CYXNc1fJ06O+rELbPwcFibSFA2kgeEfvsYg75++U1MvWnnOehSe3Cgo99fWS68byOGR8RFbdheFGcSDZW5qvxoIUtFF3NItQ9MKAYQXfGqQO1o42mbLYj0/TxNN4t8cyO7qtYYBUG8ProBSUxN8iyudAFYJkh17FrFDhTgVhIN0S/Tigt6YUSxqgVAMh5gkRvqdBCF3IIYdlIRaS9IF/TyLqhkrU9e5r/eUFwMwVkIl7YdzTV0YZOVIn/R0U0QOxnoWpUfDmfbqgiejMpUy5K/Uo9bBlKpF9/q/oe1BTXohIB+8oe7Kusiajdh+dUY4OvRrtORXHsrFyox787MyP+ZfluCOWPprppmB4X+H1zP5g2S4A5cDLIQibOOCn57kq2xCqEaEMxl47kxJ/1nUYn4sH2i9mdzKFxbrHQ5LFh3Az5tN4qHlVPdZfMvcM5zV+6jFkMzb+DzTn8varz6N+JI3uDHxpdBKQsUSqU44G3knQgjQsIA63VlR9fXqei3TGCuRkPhQYC1pWcwM2oe3NtKnihQ==
  template:
    metadata:
      name: dreamteams-postgres-secret
      namespace: dreamteams
    type: Opaque
