---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dreamteams-rustfs-secret
  namespace: dreamteams
spec:
  encryptedData:
    access_key: AgC07TyFAdc++LdfHBaZMTFT9FuCmncTi9zD2e5n+XmpZoBUXjgO/L0ioyUen0UmORyypHAccHPOrdiqXMRkqrm6NNZfwnsMpSEAtzX/ipOItPkeRCPdJtjlxCXvwCIsyfExx3bv7885pOEIPg0euU20hP4O0DvTkpI9wpmGITF7sFaTSzmFSWHLZrj4KuOOmBnrIEKASgQwAvPzXBG71WacZs043tkgcN2jDDBsAgeUppdXZS+Weq6rTC/lTwH8WxVEA28oZtPCFGpLXVZYIIiDNaOcqw9trqDcjR7GWBDdSIrnKhABqXqDZIKQEBntRSZMQyIeU1SDqSyH9xBao6EzIJUWRlsJvApg5Jj/nDCHlSWp/W3AvkhMXy57HZ9qQi0B50XtWCXaHZg42N6EUqe64yuCyOgMIqWvLpdp2iFrmuSfP7cs28e8X/l0rqhN2YsGJCgJ4ynBB5IJSM+3elBBF8igybkurYvk57VMljB9KjZ2VzFq6YswbNVARD02EW/OEm39cZpGndBXlfWSXU1gS8NyegVfFm6wKHTX/A2Jf2iSs3OLU4dDGLBwoFCFEIFINt2VUDlmT2XoZbvbohe82PtqoTyWyi3sLNnIsBulSv19YVmvOgtoa2ESoTn1CRTTvQTjHdTYToIVbFvf81a0sSqIh19lXKrWey5lMx19Coseyt2khWkwqOrqFT+SipJLml9pRVAMC3GYSg==
    secret_key: AgAupzuw4gbpq8LWJJE2svUxnRJTtB9IkFJ7dHqeO5EOXUi9vkZ0vUrBN3Wudh4XR67pS2viFXL4vNym9gTs5TKW5osQLuoW/trCsubxr/4zpU/iuAyXns3R9V3oJSYjcI+XMbdezvPJ+M97QbHI6OP0l+xfmMke7zlpm50JDZzEqbB13gkXLj3bf4FusfrAThFPbkevJrqyC+M5lnmyhYXo7z1R55nlaoo7LJv90uZR5r5IfxY8mNTVP9CuGaCR/IJtBURMniGwDMORk89Nx6MeI0h6k8urWXWg/KSUxcH036T6bvgWV9GsuJMRZSDBFIf5W7aLIvaKGRpNkS1rgUYjXI2pfQgfZN63oaM17kgEkIb+1Mz9S3psFQkjHNssiU6ZP9Hu/OSZtvXO1ZIe8DXx8XxkTg4yBx83BXtnKHCp/jJNoTAHJs6AXx6ANDGNyUu+I6X4oChNkmXPz0SqOeGGOO+WOyO/7QeS0OqFGq7UeGhPqydN4CnPl436Dpkh7kajcJxL+6/QCshA30byPgEzIgcGF9lxy/Oz+CbSWg1pyv1zgwXWZnM1vjwj4Ym4ejNGwbmLdmGjZngYzBAPLa1ceiIwqVkzSEWv3PlvkgL8DbMlrvsqpDCum8NA6CqBUoLy/KZvtw94KbflEYSgJWeDhPWqcw/fxe0nh//h/ynSwtPnYLH/SAW7TIp9Ar0YDkPPkH7MZ/y4BGV8Ww==
  template:
    metadata:
      name: dreamteams-rustfs-secret
      namespace: dreamteams
    type: Opaque
