rustfs:
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  secret:
    existingSecret: dreamteams-rustfs-secret
  storageclass:
    name: standard  # minikube default storageclass
    dataStorageSize: 1Gi
    logStorageSize: 256Mi
  ingress:
    enabled: false
  service:
    type: ClusterIP