rustfs:
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  secret:
    existingSecret: dreamteams-rustfs-secret
  storageclass:
    name: local-path
    dataStorageSize: 1Gi
    logStorageSize: 256Mi
  ingress:
    enabled: false
  service:
    type: ClusterIP
  serviceAccount:
    automount: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

bucketJob:
  image: minio/mc:RELEASE.2025-04-16T18-13-26Z
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
