image:
  repository: ghcr.io/lubaskinc0de/dreamteams
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: ghcr-secret

env:
  APP_CONFIG_PATH: "/etc/dreamteams/migrations.toml"

config:
  existingSecret: dreamteams-migrations-config
  key: migrations.toml

waitFor:
  host: dreamteams-postgres-postgresql
  port: 5432

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
