---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: observability
spec:
  encryptedData:
    alertmanager.yml: AgAXVUE4gTptBKEY19f8PBkhOmcpKD7Ypo/wlUgmxeSnyytvuWslARxkobY1L4RK8lwxKxezJjSLnz7I4plfiAS0yCCdCPePSkKNFY7/rMkjOMhmI9lPkL3bF6mqItWbTAgv44OvalBxLDY7BS3ZPRcnOJSm2RZErATi2udrI2/pQXffX29Xvpqbu/I3t1NM8hvQ5Qdx1dQBUBDdrNRHTisV531V+sOCOMVt03jE/bnfmVuWifFdzZQcxt4Vy89gXgPPxPCHqpT26TikcWgkaZzQwiEdUIDpAadcVzMCueBw1MEZvTuqXGJmKQIUfN7j7jJ/6XDLXLrx2eRxPjgV8QgGs9vsQCi6nYBx7OPN5tuR9dweHCS/MthP9Owb9sQdUjNBfusORSjZCzWJI0TCquKlHEcavk4Cjn4QDyS27ni//xvjWAk+n4KiPcuE+TcvTlZT0ymh5/G+UT81Wq5P3Klpuw87IZOqkfNPJv5DURx5CZvQIE+TRQz8YQd8NwsR8K0K2kMP3yw74eovEGeaapcMnIxjtvdQ0kuAlTuTzUchkxHpIGpHkDsZdkqcd0OvWoPalVW1uzxM1OO0ocNieG+ra4kLCgvucsmwmJh6pXz2++ANbdfziDXncWHHDEzhcHMzFx6zX7kvNdGShdlIo27lE/qSkLtwEvVSEF6LwoBFaeUIIW4FdG2/TS//AcD+Hoox9SdFXSqA3mJ5JE/n0HSzdTKgR61J+PvouQxx5OJFvPGGbXJLrXZ9D02wQE4DKqogYq5ohsJ+ImbLcSBY8SByIT4D88ncUmmhxeUd8CXm9/MJIu8lqYEPniFYNNaeSYYIDcarIT5XZnoU5z4YTyOKjrEZHLN3gHnDPCBikoJHwczbZEWxujEJIgNn6H/Z/5oUFSkp+AS6/6wNDJu6TIZ9bO/hD958At5Zw5vZoORBN8dO2gNjKKcKUokrOGpSqph045VzDl8OgL33B/UCd8FjESFBHkKeRCl6+GC+Ku0m0NaNhlbhgXpqD21RDUHsV2rEwLgK2fRj6B1enNOjKGDF9hQfkDawOTQrjlevazR+TLM+k/5bR/3DNXCjcGBi8TNKn8zce9ZqFkoV5slJbjeq0fexpxA7iytEvgyH7UV3Dcd43hzEO/6GgjtNDs5cYusB+P99sXVwtOUrf/487v2fr0AzU96DJFl+vgaS29yGQe9zC0UD5zBGJltm1Ep+14e39C0y38X7hfF0QTBkwhNwLNvLc6mlaAR1MaQbUK9u4q9wdclLM+Vx5JaV2PHFDiS52SR1/Fw3t6PmoxOsuXaVKxKO/7ICLi9HoEJ2DSe9
  template:
    metadata:
      name: alertmanager-config
      namespace: observability
    type: Opaque
