---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: observability
spec:
  encryptedData:
    alertmanager.yml: AgC/+zQDB8trWNvJ3ZlRyH6l81hYXzSxkLWeK53zxR3zJz/helRO+v8Pvhl95R+MAVMwMevBK/XvxfPWtfcCGGna1oq5mtx4VM0J2/5qjT+JCIHisyJ5cvgZDq9pEzkNIGVsAeCAHpHu8IIXItot5lBm2+86QjAXRfK33FujEka6Sy1IW+mFBEiiCaaxl1j6XpgibQgpXlXH6eoZlwK7U+J9w7BJSPr2WHJz5QeBiqM+fB/Y+mBM5UujfxtPansRNrBbHGl25HI7hGWYvewM3HplPo2zWmdFi6QDzW2SzanoT4D3fxp5W53MqTkNNDSnqxg8eTH++7kpqKeepbjEKTaNcjNnKlveTWS0pldWkbzjZ+wcKFAUMXmjktMrMnlqoMEd43aFCO18ktMs425Jqm6C5DDmWIOtCh2w2l6WtoeXtDaTbGgq0kNEM7v0dLhOozOodjPJ6+NND+KYvpaGirEnHCcJ0nBOOCvT5gad/GwbBQhBDNeimmFxQvNkuIjigVqWxH6yEhiZLw6P9Wooi/IbJnO/rfR8gz69rvQdwK2WqhS4/MTOI7Yb4zM2WnYIvQ6cHDLIMGcArqNx987BmDSvFrDg6VfVlTqtx1UuwZD4TfZhkxr5IrerIKShiTy+QX8u5Z3wBPO/Ay9xC8VOunx7aQnI4Ui3VuUmfy07Nt0cExCQzEUp0CvAnmqMy0Lrn+3IIgiUZcqOJakRiinZRvLeWJO7oK7vcf9hRGmRaXcgwQ8SA1xQYkizykcWKbaQ3TrIY7+25HtZt2/IlrlZkgUCMieGMlE5yURUdMdx/jOYrswVxE8kgI7nfV4qjgrhLCEuXVYymSd9DuwD9v3cpqE4jsxMCkYzy7IzcG7ezqZoORxmWn3ZefPFGSHttbFcDu6XLRNkVsu42VYWWzC60Oa0FCFX+sW0an+fquSabKxeZdMd1SpLrHr3TAsrS15xJJxao0o9b3f8g2MynAq2tcHTAwg+SDjYPTH8D/wuZ4/+QAUtaSuLdpVf3w5j1z1gTT1bSzrojqcQHnHJf9ybQqsB+hDPD1HQo8RCYAE6nLfSM8y362UU8mrUALPr6+fS6KLxAb9RMhhgNUPW0jQlpiF1eLoNo86Ny4ieBYIa+A40jXKFm1utFLAcsazKSHKaoRh3BtoOLfbaaTagKa3TIRUH/dkqnfSYj3aY3QRF2SuDrSaZC97LWhVmUE0SvmPQkzoxZM7zyxSSPBcZgUay8dCs47yxOvC1b+gP768VRWvPIy1yzCMnWDDmnOt8dL990T480yDFjgI2scFEY1EE/GNom+k9hBI3/ESQ57tgIY2DM/trPaiRIPHTaupcqng3PBlpfw==
  template:
    metadata:
      name: alertmanager-config
      namespace: observability
    type: Opaque
