---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: observability
spec:
  encryptedData:
    alertmanager.yml: AgC2qBZqpFQ9ODGoB1NijLaBME5ziJQzDkzWA/TyPsDTztMNQJ2GnJtCpVMK4YdDFc0KsSKgQQ5ZSMzd14xqRzbzcUli9KEo0SgTfssc/dkO1k9R1NzjFOwePBjqm9oKrATKvXvvgUAkwLRM9EH2BPA3AvIvxGJYegM3686t9rejluQCJAIxjxLdPeoPs0UAcWMtzN+5FyuHQj0nJniyzQVErD3e7OAO4YYoI307Y09C7rQqVCe70bljiAH+kvq/459GNeD9PvzoYPkdrJbEu/u6uS9fdguMFQrlmBXZDrSqe1VoShZFqwvl6tvcMb/MXnrD43jpGMf7Mpk15ZLJzWzuqu9n9rz6hhk9kCp25FwAaO7JHgaRReKBQo1uF2WT/pLQgWjswpF+4WyAVfIK9LhJ5L68Xefqt441LDLgguTC9rjWcYPwpcQerBDVPzRKRx5oaSpW8onCA80Sy9He3gMAZ8Y6kySb6dRR/dAfbWP7FxnC3tujJ8bCVZRl5224DuzlL1IG89GfbVpQZAJ5kevuDK1TWMCWYakHRlW1rszgDrmFs6NEElEfU/6S1+Z4+NlcbtrDrztVsoq1ltd2ZsuT/frY/5yy4u3C6B9BX1Q4J/fUYjRp0gY35GvhZwkCtsUEnAPgxc/pzS9Lg60WcOtXuU9mrADQzM9xUFfdT6g/YGqdG6TpWwQwr+Fj7tf7iGQa0gIHWAGrP60wdfd20kLnMWOGDfeylBanTnGywxtPoQ1iHgKKr/CISne9oPNMH+tywSwqzVSRpofCgMRSBY3DICgxVDRIMpTAVdLXO//m7JO1hQgiMq3dZlrIKSP2tDvVJ+4buDp697cILwcPmIr9O1EiAnDEegOVBMUOY7pphv30uimRGupe+NIiQBdhb3URYhA64dJIsxybF3vJMiAUIX6AE7CJhngikYg1plYUmT6P03uMcT8oX0yN53fqvQvwdSnnmQoPLednDf+eebFFsMtnoXyrS11SqBL7OVVGyZS51RAkRtbYLjH+Ohfqbtlh66VR4tmv8cVVopMuwc8czrddx+iK4hUv5fyZfeYi32EIcNpECjxTwav7QvD6Rn4DRKFaPbj2CkXdvdlNHb3DI60Aauajd9JE2Tur++RDX6zcrtGyw8NJmEcoocO75gzNb059JwvTjvr1LMK9mwHv6+c5y1pzhr47W+UU0Yz/yADWR4j9xG5oFbT+9COBANOBqoim6OUbHZtVcotTBTpRR2JZhJfyRQ==
  template:
    metadata:
      name: alertmanager-config
      namespace: observability
    type: Opaque
