---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgBkXe3tv8gm2seOChn93kQSy9+j4NiIADexaDG0GYyeR5ECJ+2P9lypV/2Gkq7whqBL5GjVnh2y00eD1MAVeFZjuX99bJCzjSGixXAN9g2/QTXDbTf8aF5RukvdPNVd/RLLgLSFbOTnlwmFZaHttSASyTI09XZbpioaKTQc+uflh47glMWyQsos7TF9RVPsvUDiy9LJ3qfJ0sU1Rd5q2+d30Bh2R3OjJwUUOfzV9ixZMqd8qvsFgCoRuE9jyEmioD6R+tUOm62UOVqtxWFnIQBrF4irO/RmU0oT5GBi2EXvMUHBza0/VTfMAFhti+PddQpsj3u3BpDUrf/ZGiaHrpE1yzhzmRNY9M3yG8I4sKkwhGVPg1Sl2Ubfe988eiWDOiqXfHHE+Qwf4KCk6mpa/b+gbzTU/Kg49Y1ZcCjQMbfubeJrzjUwJ0ssTuLTtiJWCbDvUl1xHpfg6iEfut8C6iUjmBjWCFZtpprVFFKg4pFLzVXs0O9EyQF911MnSQ2kJ/DUhfgKlfqqaM3dhTWiRkWp6qZl3oYqpkvFfcj9dQC1jfmDtXKGpW6wRPdrrwlOPhVPfQAheDEPQJZEZowjcmoifV40oJGxJfGH0wQ2bvv1eY7a2PesSLNg7UojckrZsDhoq77TPyQ09UT8/vjUrnsUKo5Z5WrZqIkQWRZ86C1cwPom2HrgCTPtZyx7qXsVmCCbXsGo6q3BXzyVqjRyf373P/9ZyaNknNrTZBSmVBSPsZZFtqgoQ/HgsNiAZw==
    postgres-password: AgCAORcP3I1u30yZbXGub1YrFPnPkyLzO2qPY9ieqcIsCCAK/ZHFIJsB/TPqT44RSzb39kvYaAMSsMJghbuLQ+paS+cJRY9FEYMbohbHL+sR/ptbH8+nRZ1sP3tufPn0xsqIkbWW31j09rGbYovZvSnFEt3QMuZNVMOGqBUo2DP7tgqos4xERdlKEXL74y09/MhYDW3ZwB1vxwvhLKhQ24rSFezWa91MdTD2/e8i7qe6al+l4rcgsTwa+lVc4tTvs+Iy/vu4ZR0HIb6YWQ+TAfubwSWXMSZzTtwoSKGKPvBlEV+VzQIMa3b1zV/lyQh4U7im8HslXxzyyplrHv9W7rR4MH7rFHTNKSYZp4Vzb0EpmcGH9POitoawI+mNohomNP4xVZqDrx6SQOFfIuxOSIPCRTSDplo0ZOq2JfRJBLS6dv3hgf/Gfa3tWwfISiICnIdXtyVPuhIpmaDyLXNHHNmlINNWa+kS38OiF8e+y6pnMy8XYMROxWXVWRsfwfA3XQehziHTJiaVL5CCDDILg7tOCiPHkrWNUt2sjItf2kh8BzWYK1Ej+qGNVl+N9VNrYkcqaekAwEd61wdYxDxOz0fOehHJbhJuMmbMJhuzwCHJ8Zu2ZUKlDlIZPkrHXsE2xFH9FJyVCmqeLtYcv1FvRdjv1hzCfNy3l3SWy2Cs97Xqoc6P0aIs6fSNXL2aAU/cKPENRlR+6oZaB9WtaVprWc3jDH0EiC1gzCOwJtdd+grNDgh5uHErtq4VvDu9jw==
  template:
    metadata:
      name: authentik-postgres-secret
      namespace: authentik
    type: Opaque
