---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dreamteams-postgres-secret
  namespace: dreamteams
spec:
  encryptedData:
    password: AgB1Y+1o4+ENHelMVBlp5pRgnDDskxnM+9Y1bSHEGJDDB/1zH74AiI4q8XTxD5fbZmMyAlo1Snf6c9shsVsixiYRckvV2NBR0xTwB1zFfEbUmXeaZ+YTJBX8c8OnYKXahVne7pzNRHuuxlY/R3thmzMopM+5ST64SJVS9JY9P9/55TAO84Z9TEoNSHOCrJneEVZcNtJYRVF7r4hQd3tGBD1aoSW0mf4CDr2nUfsOMX5u8ZHMr7PTMM/1JASfB1DiI3yjXQ65PgaSfcoeGYEc8VeNEd/dr5nQz9EX976m0pXKUsmSdzvMZnseMX0M2UYnG7t/swKOS10RCiX5f9Yx3RyOtVI10C4GlqQTGpQpLYtu6SG+cO+tTwMgQXSJZOl7RCLcB6CkYOOCWDCtaGgKfyZnVjeS5gfI4lf4g1Zt/BYpOLhyjrqmGW9pL4br+nnK3Vw8FbJjW8FTp4JJvE4ZQ4M++ZTfcKKidOFjdC+XwYhVkn56nI13CyVlBqaG/HB8zeAMYMoArQRQO7J5NQPD/IFvI8pS5N21SK4TRiku0RMhf6EGjBi2bKzDPY6GvvDfid6h007WYD4K8uJpU0yxBJFTpKFPIF4fTRgt1R7qXDvTljQr467VYlJclwkn0Aa4rredhZG3POMhZbYkqyHwoUmmhbSqDmPIIgVPGIwVuHS10eFEixkz2xSl4gPTWbj+SGVx4Z81fOoJvjC0yTuOWsHT5UnreRM6KRapo9yIgnfXTDmyI8wQcpFVulYJfA==
    postgres-password: AgCw+vBUIx6Z+0RawbprymytS79xuhfo6udar3410FCojRSIM8ZWWd9WPvEm8MvfRhGwPXVxdKNZnIjFj2W8qa/3sxF4us6UYCFUJYR6jWrB8JqC70HdnDm4g8RBjMV3lYzq+ihEn9hdohonqEqunnaGjT/+PZCpFqVXvGa5PWRxC6WPPs0r6fmz8lLobkczE1mPd8l3TQivF0MpOf0TiejHI1iCNjq/vC/WJAV3H7CP9VlQRxN4UVz7s2I5r3vdCc2VyMjgmiW45/evgtcJ27h1J8m62KGXffQNYvmfdFskU7oE7ajRFauKUrQ5s4CvzfBqN/VA7CYWrvgbiGSJNYmAGqFKVo7AKe7Q2d/w0xFYZzhnOFj7fsdQGvuq1RK4JGlgnhGd9Qu8J1QvWrfalbbXaq04NKEWBEnQfQqItUcv+YfWPjWfKAHMOHhUrq8LGYxGfPwcL+fW4OA27qekc5I77V1aboxeS9o9Av6ctOmX5qBGZlYrVr62+qKjQeYsqG7mOyB+e9CPJODXKR2HS4g7Jc2FEAKqgclW+u/X/vqFUU2OiC9LUwYrm9ngaM5llPLh6a1wR5/IrB68UxjdWEucsSfp+SzDzIYhMsKYO41WqAcVrn2WtVYdD6Q9oWCM9uN6N1MzW4LtEcLr4wm/kqSRJZE1xN4G8RlMgMsblsn7zsi9UhTE14GKyck2DZCc5BYoJjBH+BAwSx9hlc7rd6sIV/Qu8Tq2t5Ezks3ZWwHeczto+SSVtPCclhKJQg==
  template:
    metadata:
      name: dreamteams-postgres-secret
      namespace: dreamteams
    type: Opaque
