---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dreamteams-pgbouncer-secret
  namespace: dreamteams
spec:
  encryptedData:
    DB_PASSWORD: AgBuEmhmZ75a4djvrjWf7Jx6+qUgjXIAoiGjgKbqQLgoAgLy+Q7qSoYDinqlYK0yqEYgTdlPqUYEpu6+ZdjLf8tRX/lzFanv9mfB0ymAch1rrXz6+2RVx1JchNbC8eJrynH8plN4c6ggcM3YkzsXckFH0czu1jXjkMNmfPbEw87XXsGqwXQzA4nXpnDtgVj+8rIV7KZjNbdD2MYPw/seOiFkeB3L9h0LfkDiZ8oEmJvh3JOh41tmUWmSTNFWd55ei8hVfMtxAEcJlcDQ6IG32cwFXg2jlNbIZu/eV+PrnyOiSSlp2LFj9JX9om/Q/6NQ1mVueCd/HF20jV/zzxFQqj3NyLXCDfgld2tsyZBsFQPEUf+d3mUbU86/Vw/RhAvIqVCnY41PUFVsZT9bkWhPgQWRaKCzen4wJEGDPR1fDFNqYIVp9qF9elDXyOUOh9TeIfxR4tvq3cYdUFvQRuY20cKepvBP6Sv3FpNGXTmR2TTIyfWU3nkBTdyOBwHSymj1GAv7dSFBZgpH33ZKWSWAMVIIrPTQp9MbDn4BSo8/IsQNzGU+GszrUslQ0KDQpt88ZJUOKDdFOnEqYyhNc5qrTTPdAOt0nPOKFtXgxKeH85coaVHJ5jpJvKyU7gd95DRmuEbt/VQSJJaXvxPGPRiYhFd+8u4fN2ZdOF+0FKFObEDlmlLb/Zcfnf4U+nvshjOW/aSBqEb2blEvXqZkWACU0iHr92rAHm/+7RWwjyhWp7a3YqF4dGTbYnkXoTHyqA==
    DB_USER: AgBsG38xTjO7aI5CZ1JCkswSvmiEiIXUFr7QDKXZIKmjfTouukZoBcqWa7YGrLhvxnaap+s1u0q4MzKV3HpK1oTee/X1UBN6R6Evl5SxrAszvrlRDNbT4dcUiMAXd6a/qAjXcYQOoBtho1/UPoTu3+Ogklk3KZpmTJjD4PBWwzKC+uvC6v7w1V3CtsCHB52bSjMQ10slgehBLqJNEIzx5uRF9rUrbs3nsYvaiBs0erEjsY6mGpUVa9O+PFQqBM0SwK0IUDEZrS1+GSeIZnb0/YumlORw8LuXYI812+G6G5QhnZw7Tl4CESHDoCBB6vGJpoS87LPvxCBhSK4MUvXG+8OU5zhKgKbWprbn8xvNzPrZybOxeUC6Zn1Nn3A+nBioeLKtct8SfRhoW9ojcT4k0+PCmo6WjuiW2xlyzfRdH/L8RitduNiXiKUzSmtSdei6PsmG9Yqm1bW9F0cqqo62TqbS3zmYVxObfOed6Cf1WPk5JroxcWy2trc/PqglsBg6YVHoMJ77dcrStvCFm04fWQMUzOblTZb3hpMdo2+vDl7gWA7U/vxhDgvEn69QimCvDautAmOcE5X5hv0ylxxAP/AxItyx+o6cJVCZ+lAwi8tRTWrC1ZQFuJ0QecQTbuDVXw1Jb2GroMFZU+TmjwTwCYQjNv4RyBgY7KW/TceaaJgDUaefpmKH1jrffxzu9wMLBOsAj1NFoVS72A==
  template:
    metadata:
      name: dreamteams-pgbouncer-secret
      namespace: dreamteams
    type: Opaque
