---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dreamteams
spec:
  encryptedData:
    .dockerconfigjson: AgALWEe3YNHo4vJEYJFIuUnJIIkxJPlU3ttGe1pWwT4alLqCIGUkPzYcDjeInMfxGO0lIsjkPnj8XzRFyS6usnbjmvN62507mtEHap3EkwvZcju45l68KhLlYByfgY15/IUJNI4iincQPY0MXOniepQKEbMbcMbhD+NikJMxFB33Dr8k65hxQNqFEfPe6wRC3Aa4miwodeKIxieqYIlFSXPZJnUccVPCygFH8WK7B7jHf9+znyTB8cnltGG5j/ugPBUXVwjrygMMC4uqIqULtCfNJ5DCcfzN6vvXiMa1CUXS+nX3TFFyntYkFbEQXrxZUQZ+QeM8b3/3XDgFHlstepCnvyD35f7QG002V6m/v2YQNhB0B7rKkckYvch29CcmkSN1Q04vxYmYntcRiA50Wm0IuEe8jlOholNi/g3tZlTP+y2KdkrbNi53oPUctMrLwfTuXyl0hKQtR93oxwKG+xrPPJ0FQIoqO0229Pod0JdKc7VaDSue1oX0TkK1Xlrtu/wDlJtqpGo290C0/m1G5E0ruEhwtYIY5svICVdCjrapCVdsQIQKejOdVeNulBhm8wAk4KTAay7zlet+qf9pyl7m/CkVuKVy0tUTvcIqkW8hG4GzqDEjQ/3IHCSnrGHoxSOGxn04Y0LlrB4gSBym20FZxXxOydCknohd4gEvSyNApYDo0BsSg912cE5ucISG02e6oHxKtdJhzV5/SNFzwXxa44cyMeT4JEPE2Fl2bR3pbZMxHxOXIkBBRN8Rc1h/nFZdfR9Cy3NPWxZeBDwLClVZuOZR4Fs5sAEDi5PYz3ewRP2aAgnUcNUYFzb+PcbuZHtCnoovsbb7nPWcgIVnIvFUkkzHXl7810H3qsDT/CcYrzg1HUK169xxfYHJyARcgsTugzVGWujGgxuh2fitNSrannbjlLqQsODf3SU+MJWKo3R2mi4jQEb/ag==
  template:
    metadata:
      name: ghcr-secret
      namespace: dreamteams
    type: kubernetes.io/dockerconfigjson
