---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dreamteams
spec:
  encryptedData:
    .dockerconfigjson: AgBMVqio8806VLSqvg5r3vW5sS0vSXpsTvNZ14JdYhWZEFRg+6EgOoZBx5rZmvJuRXSJWW9LhQmFdTRAwbSRYTcX8KPY0Bi8QQ/dF2Gamw8HOEcr6bPjZUOJzv5ulx+9DUV+QhkI7gBLQoFrrWHQW0OOs0s1KaBYFLc5cnz3b1M5VkvIui1wVLJcJ47vaNzoOFTDR0NjAl9wOUxDmjFEkixfkqAagh67iG9Cu9G78KknISdc1NDQFHGzT3HtczqkZVcEllAkNh8nGfstuN4SVA5q7y9qrZR7IhmKHe17uenrPKoRPzO9t/h2tXb4uiHYsSWJnrwm2msS0ywUKMUoggw8EQNBL/pc9W3RScLrpxJIUVUuOfBl0vI+DmLSNWixlR2OJGqh+P5QVb45/VurrT8TEhSWgukW2GodGBmTpdGE/ru3HzODTEi/6ezhMnTVDIdorL/zTATzuBotqWR0KGohJaWSHNIgZqpm/bXftSjibBxQNxLwzuOlclFQ8qXXlv57FT3hFmO0ZwCObpduEebkXF0CqIcbGcx7D2R2WWkZpKwALy67ajGmaq8wuCmxCuu9vTrI4Tur5tSQe0tZO3JYmCNgXBOON3DKnP71Xt0wQH8QMPlICdEs0IHDt7isEcINXglcWafh3VKtK1H95OoUE7FhauGx/B8IZ1PwC9JKZYD6ckuR+upNCpq27UjLg8pKcsNDiQJmpM91jzr2fZJF/oRTsgP05tQ4dCk2eJxOnDXPe9WUKzhQXHs+RPiWnbLFQLHL6l9PO5XGE98/TQ==
  template:
    metadata:
      name: ghcr-secret
      namespace: dreamteams
    type: kubernetes.io/dockerconfigjson
