---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBtYf6kGQfP+FxmppUPlEcGozSVVRYdHUON6/xBf8wVaFHrn5r96VYbjk4KPArprZUHenomxU7kYxj2b2G6lsKxCyigw+ZJmWjpOm2XS/kdPw3pLUZiUEYC1fx+s/0wokt0WsiFhee1pLvkNy/czlSlk8rXgGVOrx1T2t73cVRnaZ8W+KcQ+At2wbq+/KY1b9TpTAq6Iy+Jrkp033CJ+oaG2XhiPA8dr83N9nAXfyux4UvRFam3Y9NuV7mkwsXKQhrMLv/jAcvElncCFsNLtS+70JR/IsSw3xRud/Xl2RblDawtVeXK+/BP0DALAdW0LkJf5K5ZRRKZOf9Z1Fyja7eZRhSElXJL4gBoKmzVdfgNZhdcj5AhJpMAic492lOA0w9kE2aVwYZ5/Sqcn90uHVLcs+iumC/aS10iS0nJhTGBuc0vTAEIqvndQ8n1hd5wiXpUZATcWWq8jRseab6qIuvWZujDrFN4Ap9EtjnAf1NEx8KNRios0Gaw0JtNYqz2KMELkA3rmbWfM/Nrh85nsuiEOwI7r5taLAYr3auVyOqpBwyuyFu65D4afYv4/pBlI0F5/wR3oAbsosL3MDbdsXzrlMDpZMLRJ50+quOpFtqZCfP9hUYR1lAYkCMsQ4cnTSfqmcjmjXsMw7gtj5FOyWk74W5M3UpYh/oTYtkVXIUi9HYU16/h4A7OVIB1ekO2gkS2F5K5HvG3WJN1RlclpSJ40LXYtrkQSfh14GG16brjDwdbyb9V3bTwCa+E7A==
    admin-user: AgB0FNglaAC18k8zXcKXJ/ZRLQV2X94HrDcwqgnEBzIUiL64q8rxmsskCU7X9tOKNXSBqfXU29bFDmIxDr6Lz4gXsyoC7Vy4gev2TzQsAjRK4s/vbwEhannaeTVjDMULd8fN5PUSMvSoxGYb3fjyi9JgqALU/UypYhUPS56UGDoEn6+9MHy3IQcJ65jYgVmIcffkdcpo9cDJvH3QzP/TFMGlAoPSfbj59vLAYWXwJLsCOgn4VTchnLlXnmPPIMUFbyrvcGQRY7+SpXLhMXddw/tAGwB1wJEo78pe3zd70fqOM7J1bAG4+z0bjHyEuyOT8labRMrOq1hZjVG87tnudBci2gqwQGtpQaGiZhFeFqMAsajfeyw9ZarpigHp3Xp1ib5D2GBuxiLLBZaoJDmmtFTUUJ9w38bDlpuumkpZ9+MGi46HE9A4vMWhs67doQolzFPHp1IXNbMbkrZDPv2PAnJE4FddocpF1KydIvMKkWNzOk64Tp3rs1E+R+RJl7mIdfIstwsEPESDJS3Pn8e3+YGaVLVgyYOxNFQZxZ72QTz3bhUudQfkoxsBR1MM9KS0wyOW+4MKpHVlbHGDXvdgZ96K8jK8aG2RLfMW2v8SiP3aEvT9qQViUcCFUGg31frSzaFgzcl2EGcONf2ROpN7HNzpwHGQFhgVTNj7tYdvKPyYFN7sGj9yROB/wSNphzuBjp5Os29zgg==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
