apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "dreamteams_exporter.fullname" . }}-api-5xx-rate
  labels:
    {{- include "dreamteams_exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  metrics:
    - name: http-5xx-rate
      initialDelay: 60s
      interval: 30s
      count: 10
      failureLimit: 1
      successCondition: result[0] < 5
      failureCondition: result[0] >= 5
      provider:
        prometheus:
          address: http://prometheus.observability:9090
          query: |
            (
              ((sum(increase(http_server_duration_milliseconds_count{service_name="dreamteams-exporter"}[5m])) or vector(0)) >= bool 20)
              *
              (
                ((sum(rate(http_server_duration_milliseconds_count{service_name="dreamteams-exporter", http_status_code=~"5.."}[5m])) or vector(0))
                /
                clamp_min((sum(rate(http_server_duration_milliseconds_count{service_name="dreamteams-exporter"}[5m])) or vector(0)), 0.001))
                * 100
              )
            )
