apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dreamteams_anubis.fullname" . }}-policy
  labels:
    {{- include "dreamteams_anubis.labels" . | nindent 4 }}
data:
  botPolicies.yaml: |
    {{- toYaml .Values.policy | nindent 4 }}
