apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dreamteams-nats
  labels:
    app.kubernetes.io/name: dreamteams-nats
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: dreamteams-nats
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dreamteams-nats
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dreamteams-nats
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -js
            - -sd
            - /data
            - -m
            - "{{ .Values.service.monitorPort }}"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: client
              containerPort: {{ .Values.service.clientPort }}
            - name: monitor
              containerPort: {{ .Values.service.monitorPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitor
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitor
          volumeMounts:
            - name: data
              mountPath: /data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.jetstream.storageSize }}
